version: '3'
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    container_name: 'gitlab'
    restart: always
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:6666'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '6666:80'
      - '2222:22'
      - '443:443'
    volumes:
      - gitlab_volume:/etc/gitlab'
      - gitlab_volume:/var/log/gitlab'
      - gitlab_volume:/var/opt/gitlab'
volumes:
  gitlab_volume:
    # external: true