version: '3'
services:
  web:
    image: 'jenkins:latest'
    container_name: 'jenkins'
    restart: always
    ports:
      - '8888:8080'
      - '50000:50000'
    volumes:
      - '${PWD}:/var/jenkins_home'