version: '3'
services:
  mongo:
    container_name: yapi_mongo
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - yapi_mongodata:/data/db
      # - ${PWD}/mongo/db:/data/db
    networks: 
      - back
  # winpty docker run -it --name=yapi_mongo -v d:devOps/yapi/mongo/db:/data/db -p 27017:27017 --restart=always mongo:latest 
  web:
    container_name: yapi_web
    image: shafley/yapi
    restart: always
    ports:
      - '9999:9090'
    links: 
      - mongo:mongo
    volumes:
      - ${PWD}:/home/yapi
    command: 'yapi server'
    networks: 
      - back
networks:
  back:
    driver: bridge
volumes:
  yapi_mongodata:
    external: true