version: '3'
services:
  mongo:
    container_name: yapi_mongo
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ${PWD}/mongo/db:/data/db
    networks: 
      - back
  web:
    container_name: yapi_web
    image: shafley/yapi
    ports:
      - '9090:9090'
    links: 
      - mongo:mongo
    volumes:
      - ${PWD}:/home/yapi
    command: 'yapi server'
    networks: 
      - back
networks:
  back:
    driver: bridge